#!/usr/bin/env node
/* Vendors the Phosphor Regular glyphs this site draws, from the Phosphor core repo.
 *
 *   npm run icons
 *
 * From the source, never from another product's tree. A copy of a copy has no source to re-read,
 * and the estate has no shared component library to take one from: those repos were purged on
 * 2026-09-14 and every app vendors its own set.
 *
 * The glyphs compile into src/lib/phosphor.ts as path bodies in currentColor, so a glyph takes
 * the ink of whatever sits beside it. No icon font and no runtime CDN.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const LICENSE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE';

/* One glyph per job this site actually has. A glyph with no caller is a glyph to delete rather
 * than to keep in case. The five category glyphs are BreachProbe's own five categories; the
 * three verdict glyphs are this gate's three exit codes. */
const WANT = [
  'terminal-window', // the console route, and the captured run
  'shield-warning', // the conditions route
  'list-checks', // the method route
  'caret-up-down', // the app switch beside the mark
  'caret-right', // a row that opens
  'arrow-square-out', // an outward link
  'scan', // the scan picker in the control bar
  'gauge', // the grade floor picker
  'database', // BreachProbe category: database. Also the fail-on-database input
  'key', // BreachProbe category: keys. Also the fail-on-write-path input
  'lock-key', // BreachProbe category: rls
  'browsers', // BreachProbe category: headers
  'user-circle', // BreachProbe category: auth
  'check-circle', // exit 0
  'x-circle', // exit 1
  'question', // exit 2, could not check
  'table', // a grid of rows
  'clock', // a read date
  'info', // a note in a rail
  'prohibit', // a thing this package refuses to have
  'git-branch', // the workflow and the repository
];

await mkdir(OUT, { recursive: true });
const index = {};
for (const name of WANT) {
  const url = `${BASE}/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} on ${url}`);
  const svg = await r.text();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .trim();
  await writeFile(resolve(OUT, `${name}.svg`), svg);
  index[name] = body;
  process.stdout.write(`${name}  ${svg.length}b\n`);
}
const lic = await fetch(LICENSE);
if (!lic.ok) throw new Error(`HTTP ${lic.status} on the licence`);
await writeFile(resolve(OUT, 'LICENSE'), await lic.text());

await writeFile(
  resolve(ROOT, 'src/lib/phosphor.ts'),
  `// GENERATED by scripts/icons.mjs from ${BASE}\n` +
    `// Phosphor Icons, MIT. The licence is vendored at vendor/phosphor/LICENSE.\n` +
    `export const GLYPH: Record<string, string> = ${JSON.stringify(index, null, 1)};\n` +
    `export type GlyphName = keyof typeof GLYPH;\n`,
);
process.stdout.write(`\nwrote src/lib/phosphor.ts, ${WANT.length} glyphs\n`);
